M48
; DRILL file {KiCad (6.0.2-0)} date 2022 July 03, Sunday 14:43:15
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-03T14:43:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X4.9331Y-2.8711
X5.878Y-2.8711
X5.9272Y-2.8711
X6.872Y-2.8711
T0
M30
